export const ideologies = [
    {
      uid: 1,
      name: "Psychotic Dictatorship",
      economicFreedom: 1,
      civilRights: 1,
      politicalFreedom: 1,
    },
    {
      uid: 2,
      name: "Iron Fist Consumerists",
      economicFreedom: 10,
      civilRights: 5,
      politicalFreedom: 5,
    },
    {
      uid: 3,
      name: "Corporate Police State",
      economicFreedom: 20,
      civilRights: 10,
      politicalFreedom: 10,
    },
    {
      uid: 4,
      name: "Right-Wing Utopia",
      economicFreedom: 30,
      civilRights: 15,
      politicalFreedom: 15,
    },
    {
      uid: 5,
      name: "Moralistic Democracy",
      economicFreedom: 40,
      civilRights: 20,
      politicalFreedom: 20,
    },
    {
      uid: 6,
      name: "Authoritarian Democracy",
      economicFreedom: 25,
      civilRights: 10,
      politicalFreedom: 15,
    },
    {
      uid: 7,
      name: "Tyranny by Majority",
      economicFreedom: 35,
      civilRights: 15,
      politicalFreedom: 20,
    },
    {
      uid: 8,
      name: "Conservative Democracy",
      economicFreedom: 50,
      civilRights: 30,
      politicalFreedom: 30,
    },
    {
      uid: 9,
      name: "Free-Market Paradise",
      economicFreedom: 55,
      civilRights: 35,
      politicalFreedom: 40,
    },
    {
      uid: 10,
      name: "Corrupt Dictatorship",
      economicFreedom: 20,
      civilRights: 15,
      politicalFreedom: 10,
    },
    {
      uid: 11,
      name: "Father/Mother Knows Best State",
      economicFreedom: 30,
      civilRights: 20,
      politicalFreedom: 20,
    },
    {
      uid: 12,
      name: "Compulsory Consumerist State",
      economicFreedom: 45,
      civilRights: 25,
      politicalFreedom: 30,
    },
    {
      uid: 13,
      name: "Democratic Socialists",
      economicFreedom: 55,
      civilRights: 50,
      politicalFreedom: 45,
    },
    {
      uid: 14,
      name: "Liberal Democratic Socialists",
      economicFreedom: 60,
      civilRights: 60,
      politicalFreedom: 50,
    },
    {
      uid: 15,
      name: "Inoffensive Centrist Democracy",
      economicFreedom: 50,
      civilRights: 50,
      politicalFreedom: 50,
    },
    {
      uid: 16,
      name: "New York Times Democracy",
      economicFreedom: 65,
      civilRights: 70,
      politicalFreedom: 55,
    },
    {
      uid: 17,
      name: "Corporate Bordello",
      economicFreedom: 70,
      civilRights: 75,
      politicalFreedom: 60,
    },
    {
      uid: 18,
      name: "Capitalist Paradise",
      economicFreedom: 75,
      civilRights: 80,
      politicalFreedom: 65,
    },
    {
      uid: 19,
      name: "Benevolent Dictatorship",
      economicFreedom: 40,
      civilRights: 40,
      politicalFreedom: 35,
    },
    {
      uid: 20,
      name: "Libertarian Police State",
      economicFreedom: 45,
      civilRights: 35,
      politicalFreedom: 40,
    },
    {
      uid: 21,
      name: "Iron Fist Socialists",
      economicFreedom: 30,
      civilRights: 20,
      politicalFreedom: 20,
    },
    {
      uid: 22,
      name: "Scandinavian Liberal Paradise",
      economicFreedom: 80,
      civilRights: 85,
      politicalFreedom: 70,
    },
    {
      uid: 23,
      name: "Left-Leaning College State",
      economicFreedom: 75,
      civilRights: 80,
      politicalFreedom: 75,
    },
    {
      uid: 24,
      name: "Capitalizt",
      economicFreedom: 85,
      civilRights: 90,
      politicalFreedom: 80,
    },
    {
      uid: 25,
      name: "Left-Wing Utopia",
      economicFreedom: 90,
      civilRights: 95,
      politicalFreedom: 85,
    },
    {
      uid: 26,
      name: "Civil Rights Lovefest",
      economicFreedom: 95,
      civilRights: 100,
      politicalFreedom: 90,
    },
    {
      uid: 27,
      name: "Anarchy",
      economicFreedom: 100,
      civilRights: 100,
      politicalFreedom: 100,
    }
];
  